### ISSUE TITLE
Authentication to try out the package

### ISSUE THREAD

**Issue by montesmariana** [irods/irods_client_library_rirods#20]
Hi! I'm sorry if this is a dumb question, but I wanted to try out this package and I'm stuck at connecting with the demo REST API.

I have run the code to start the demo and get no errors:
```sh
# clone the repository
git clone --recursive https://github.com/irods/irods_demo
# start the REST API
cd irods_demo
docker-compose up -d nginx-reverse-proxy
```

Then I loaded the library and ran `create_irods()` as indicated, with the same arguments. But when I have to authenticate with `iauth()` I have no idea how to authenticate in order to get access and try this out. Is there a user-psswd combination I can use for testing? Or how can I create my own? Or what other alternative is there?

I'm running this from Ubuntu 20.04 with rstudio-server.

Thank you in advance for any guidance you can give me!

**Comment by MartinSchobben** [comment]
If you use the irods_demo then it defaults to `"rods"` and `"rods"`. This should do the trick. Let me know if you have further questions or suggestions. Do note that there will be changes for rirods in the future. It is still under heavy development.

**Comment by montesmariana** [comment]
Thank you for the quick answer!
I did try that, and got this error:

``` r
library(rirods)
create_irods("http://localhost/irods-rest/0.9.3", "/tempZone/home", overwrite = TRUE)
iauth('rods', 'rods')
#> Error in `httr2::req_perform()`:
#> ! Failed to parse error body with method defined in req_error()
#> Caused by error:
#> ! lexical error: invalid char in json text.
#>                                        <html>  <head><title>502 Bad Ga
#>                      (right here) ------^

#> Backtrace:
#>      ▆
#>   1. ├─rirods::iauth("rods", "rods")
#>   2. │ └─rirods:::get_token(paste(user, password, sep = ":"), find_irods_file("host"))
#>   3. │   ├─httr2::resp_body_string(httr2::req_perform(req))
#>   4. │   │ └─httr2:::check_response(resp)
#>   5. │   │   └─httr2:::is_response(req)
#>   6. │   └─httr2::req_perform(req)
#>   7. │     ├─httr2:::resp_abort(resp, error_body(req, resp))
#>   8. │     │ └─rlang::abort(...)
#>   9. │     │   └─rlang::is_formula(message, scoped = TRUE, lhs = FALSE)
#>  10. │     └─httr2:::error_body(req, resp)
#>  11. │       ├─rlang::try_fetch(...)
#>  12. │       │ ├─base::tryCatch(...)
#>  13. │       │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  14. │       │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  15. │       │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>  16. │       │ └─base::withCallingHandlers(...)
#>  17. │       └─httr2:::req_policy_call(req, "error_body", list(resp), default = NULL)
#>  18. │         ├─rlang::exec(req$policies[[name]], !!!args)
#>  19. │         └─rirods (local) `<fn>`(`<httr2_rs>`)
#>  20. │           └─httr2::resp_body_json(resp, check_type = FALSE)
#>  21. │             └─jsonlite::fromJSON(text, simplifyVector = simplifyVector, ...)
#>  22. │               └─jsonlite:::parse_and_simplify(...)
#>  23. │                 └─jsonlite:::parseJSON(txt, bigint_as_char)
#>  24. │                   └─jsonlite:::parse_string(txt, bigint_as_char)
#>  25. └─base::.handleSimpleError(...)
#>  26.   └─rlang (local) h(simpleError(msg, call))
#>  27.     └─handlers[[1L]](cnd)
#>  28.       └─rlang::abort(...)
```

<sup>Created on 2023-01-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


Am I missing something? I also tried to reinstall rirods from github, so it is the latest version.

**Comment by MartinSchobben** [comment]
At least you get an answer from the server. Could you try this on your terminal: `inst/bash/iauth.sh "rods" "rods" "http://localhost/irods-rest/0.9.3"`. This is a shell script within the package source files that uses curl directly. See whether you can generate the token like this.

**Comment by montesmariana** [comment]
I don't think I understand what the output should be. I get a table with some information ("Total", "Received"...) and then a portion of an html printed.

```sh
.../irods_client_library_rirods$ inst/bash/iauth.sh "rods" "rods" "http://localhost/irods-rest/0.9.3"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   157  100   157    0     0   153k      0 --:--:-- --:--:-- --:--:--  153k
 </html>nter>nginx/1.23.1</center>/center>d>
```

If I just reproduce the last line without `echo`:

```sh
.../irods_client_library_rirods$ curl -X POST -H "Authorization: Basic ${SECRETS}" "http://localhost/irods-rest/0.9.3/auth"
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.23.1</center>
</body>
</html>
```

Note: I ran this from the cloned copy of the package (since I have to access the source code) but I was trying to run everything from a personal project. I tried to run the R code again after this and there is no difference.

**Comment by MartinSchobben** [comment]
So, it seems not related to R, both ways we saw the http response 502. I have the impression that your localhost is not listening at port 80. Could that be the case?

**Comment by montesmariana** [comment]
It could be the case but I'm afraid I don't know how to check it, change it or debug it :/ Any suggestions?
Sorry for the trouble!

**Comment by MartinSchobben** [comment]
No worries, I am also learning these things on the fly when developing this package. On my linux mint I can check this with `sudo ss -ltnp`. Also, this issue seems helpful to me, as I wonder whether `create_irods` should have a port parameter, as it defaults to 80 now.  So, I might rename the issue and keep it open for now.

**Comment by montesmariana** [comment]
Thank you :)

This is part of my output.
```sh
...irods_demo$ docker-compose up -d nginx-reverse-proxy
Starting irods_demo_irods-catalog_1 ... done
Starting irods_demo_irods-catalog-provider_1 ... done
Starting irods_demo_irods-client-rest-cpp_1  ... done
Starting irods_demo_nginx-reverse-proxy_1    ... done
...irods_demo$ sudo ss -ltnp
State      Recv-Q       Send-Q                Local Address:Port               Peer Address:Port           Process
LISTEN     0            4096                        0.0.0.0:80                      0.0.0.0:*               users:(("docker-proxy",pid=3786,fd=4))
LISTEN     0            4096                           [::]:80                         [::]:*               users:(("docker-proxy",pid=3793,fd=4))
```

Trying to solve this between my previous question and your answer I ran:

```sh
sudo ufw allow 80/tcp comment 'accept HTTP connections'
```

I don't really know if that's what I should have done, but nothing has been solved.

**Comment by MartinSchobben** [comment]
Ok, now I am lost as well. You seem to have the irods_demo up and running in good order. The only thing different with what I see, is that I have also: 
```
LISTEN    0         4096               0.0.0.0:5430             0.0.0.0:*        users:(("docker-proxy",pid=6078,fd=4)) 
```
as output.

@alanking Can you help with this?

**Comment by montesmariana** [comment]
Thank you!

> Ok, now I am lost as well. You seem to have the irods_demo up and running in good order. The only thing different with what I see, is that I have also:
> 
> ```
> LISTEN    0         4096               0.0.0.0:5430             0.0.0.0:*        users:(("docker-proxy",pid=6078,fd=4)) 
> ```
> 
> as output.

I also have that as part of the output.

About @trel's comment:
- If I restart the whole thing (docker, the image...) then I get the same output from `docker ps`.
- After I have tried to connect via rirods or the `inst/bash/iauth.sh... ` command, then the `irods_demo_irods-catalog-provider` image disappears from the list and I get errors in the logs.
From `docker logs irods_demo_nginx-reverse-proxy_1`:

```sh
2023/01/23 14:15:13 [error] 30#30: *1 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.1, server: , request: "POST /irods-rest/0.9.3/auth HTTP/1.1", upstream: "http://172.18.0.4:8081/irods-rest/0.9.3/auth", host: "localhost"
172.18.0.1 - rods [23/Jan/2023:14:15:13 +0000] "POST /irods-rest/0.9.3/auth HTTP/1.1" 502 157 "-" "httr2/0.2.2 r-curl/5.0.0 libcurl/7.68.0" "-"
172.18.0.1 - rods [23/Jan/2023:14:16:06 +0000] "POST /irods-rest/0.9.3/auth HTTP/1.1" 502 157 "-" "curl/7.68.0" "-"
2023/01/23 14:16:06 [error] 31#31: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "POST /irods-rest/0.9.3/auth HTTP/1.1", upstream: "http://172.18.0.4:8081/irods-rest/0.9.3/auth", host: "localhost"
```

From `docker logs irods_demo_nginx-reverse-proxy_1`:

```sh
Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.
Please confirm [yes]:



Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 515, in main
    setup_server(irods_config,
  File "/var/lib/irods/scripts/setup_irods.py", line 150, in setup_server
    test_put(irods_config)
  File "/var/lib/irods/scripts/setup_irods.py", line 180, in test_put
    raise IrodsError('Post-install test failed. Please check your configuration.')
irods.exceptions.IrodsError: Post-install test failed. Please check your configuration.
```

**Comment by trel** [comment]
> `irods_demo_irods-catalog-provider` image disappears

This is definitely not what should happen.   @MartinSchobben can you reproduce this?

@montesmariana Can you tail the logs of the provider *before* you attempt to connect via rirods or `iauth.sh`?

Note the `-f`:
```
$ docker logs -f irods_demo_irods-catalog-provider_1
```

Myabe it will show what is falling over and causing the container to disappear (stop running).

**Comment by MartinSchobben** [comment]
> This is definitely not what should happen. @MartinSchobben can you reproduce this?

No, I can't.

**Comment by montesmariana** [comment]
Ok, I restarted everything, restarted the demo, did not open R or run `iauth.sh` and this is the output:

```sh
(py) ...irods_demo$ docker-compose up -d nginx-reverse-proxy
Starting irods_demo_irods-catalog_1 ... done
Starting irods_demo_irods-catalog-provider_1 ... done
Starting irods_demo_irods-client-rest-cpp_1  ... done
Starting irods_demo_nginx-reverse-proxy_1    ... done
(py) ...irods_demo$ docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED       STATUS         PORTS                                       NAMES
1ba213f9f49f   irods_demo_nginx-reverse-proxy      "/docker-entrypoint.…"   12 days ago   Up 5 seconds   0.0.0.0:80->80/tcp, :::80->80/tcp           irods_demo_nginx-reverse-proxy_1
1e4d296b2574   irods_demo_irods-client-rest-cpp    "./entrypoint.sh"        12 days ago   Up 6 seconds                                               irods_demo_irods-client-rest-cpp_1
3d0307c19b74   irods_demo_irods-catalog-provider   "./entrypoint.sh"        12 days ago   Up 7 seconds                                               irods_demo_irods-catalog-provider_1
c44ee10008c8   irods_demo_irods-catalog            "docker-entrypoint.s…"   12 days ago   Up 8 seconds   0.0.0.0:5430->5432/tcp, :::5430->5432/tcp   irods_demo_irods-catalog_1
```

And from `docker logs -f irods_demo_irods-catalog-provider_1` the tail is:

```sh

Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.

+-----------------------------------------------------+
| WARNING:                                            |
| The database specified is an already-configured     |
| iRODS database, so first-time database setup will   |
| not be performed. Providing different inputs from   |
| those provided the first time this script was run   |
| will result in unspecified behavior, and may put    |
| a previously working zone in a broken state. It's   |
| recommended that you exit this script now if you    |
| are running it manually. If you wish to wipe out    |
| your current iRODS installation and associated data |
| catalog, drop the database and recreate it before   |
| re-running this script.                             |
+-----------------------------------------------------+

Please confirm [yes]:


Local storage on this server [yes]:
Default resource [demoResc]:
iRODS Vault directory [/var/lib/irods/Vault]:
iRODS server's zone name [tempZone]:
iRODS server's port [1247]:
iRODS port range (begin) [20000]:
iRODS port range (end) [20199]:
Control Plane port [1248]:
Schema Validation Base URI (or off) [file:///var/lib/irods/configuration_schemas]:
iRODS server's administrator username [rods]:

-------------------------------------------
Zone name:                  tempZone
iRODS server port:          1247
iRODS port range (begin):   20000
iRODS port range (end):     20199
Control plane port:         1248
Schema validation base URI: file:///var/lib/irods/configuration_schemas
iRODS server administrator: rods
-------------------------------------------

```

After 3 minutes without ANY OTHER CHANGES (I just sat there watching the screen), catalog-provider died.

```sh
...irods_demo$ docker container ls -a
CONTAINER ID   IMAGE                               COMMAND                  CREATED       STATUS                      PORTS                                       NAMES
1ba213f9f49f   irods_demo_nginx-reverse-proxy      "/docker-entrypoint.…"   12 days ago   Up 3 minutes                0.0.0.0:80->80/tcp, :::80->80/tcp           irods_demo_nginx-reverse-proxy_1
1e4d296b2574   irods_demo_irods-client-rest-cpp    "./entrypoint.sh"        12 days ago   Up 3 minutes                                                            irods_demo_irods-client-rest-cpp_1
3d0307c19b74   irods_demo_irods-catalog-provider   "./entrypoint.sh"        12 days ago   Exited (1) 25 seconds ago                                               irods_demo_irods-catalog-provider_1
c44ee10008c8   irods_demo_irods-catalog            "docker-entrypoint.s…"   12 days ago   Up 3 minutes                0.0.0.0:5430->5432/tcp, :::5430->5432/tcp   irods_demo_irods-catalog_1
f461fa4355bb   hello-world                         "/hello"                 5 weeks ago   Exited (0) 5 weeks ago                
```

And the following text was added to the log output:

```sh

Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.
Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.
Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.
Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.
Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.
Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 515, in main
    setup_server(irods_config,
  File "/var/lib/irods/scripts/setup_irods.py", line 150, in setup_server
    test_put(irods_config)
  File "/var/lib/irods/scripts/setup_irods.py", line 180, in test_put
    raise IrodsError('Post-install test failed. Please check your configuration.')
irods.exceptions.IrodsError: Post-install test failed. Please check your configuration.
Please confirm [yes]:

```

The with the help of a colleague I restarted the failing image manually (`docker run -ti irods_demo_irods-catalog-provider bash`) and it survived for longer than 4 minutes but it still didn't solve the problem, probably because we cannot give it the right name. (We're trying.)

**Comment by trel** [comment]
This suggests that the post-install was waiting for some input and didn't get it ... and eventually timed out.

But I'm not sure what that would be, as you're running the same code we're running...

**Comment by montesmariana** [comment]
Thank you so much! I'm also trying to reproduce it with another colleague.
I'm working with the KU Leuven team, by the way, I started in December 😊

**Comment by montesmariana** [comment]
So, my colleague tried to reproduce the issue and he couldn't (it works perfectly for him).

We re-cloned irods_demo and tried to run build everything from scratch again and we get the following message:

```sh

WARNING: Image for service nginx-reverse-proxy was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Recreating irods_demo_irods-catalog_1 ... error

ERROR: for irods_demo_irods-catalog_1  no such image: sha256:c6cf8f1af37b4e26775518deead696c81cd93e92548976c04e4d68479dd11ba9: No such image: sha256:c6cf8f1af37b4e26775518deead696c81cd93e92548976c04e4d68479dd11ba9

ERROR: for irods-catalog  no such image: sha256:c6cf8f1af37b4e26775518deead696c81cd93e92548976c04e4d68479dd11ba9: No such image: sha256:c6cf8f1af37b4e26775518deead696c81cd93e92548976c04e4d68479dd11ba9
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.
```

And again, the four images start well but then the catalog-provider image dies within 4 minutes. We also entered the container interactively (before it died) and became irods (`su - irods`) but iCommands did not work.

Do you have any guidance?
After the message we get a question ("Continue with new image?") but answering y does not solve the problem (it looks fine but the container still dies).

**Comment by montesmariana** [comment]
GREAT NEWS!

We solved the issue by totally deleting docker and reinstalling it again, as well as docker-compose.
Now everything works smoothly.

I'm really sorry for bothering you with this, hopefully if someone ever runs into these issues again they know the issue is with the docker(-compose) installation itself.

Thank you for all your help!!

**Comment by trel** [comment]
Ah, very good.   Thank you - good luck!
